services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    command: ["meilisearch", "--no-auth", "--db-path", "/meili_data", "--http-addr", "0.0.0.0:7700"]
